[workspace]
members = [
    "worldwide-icu4x-datagen",
    "worldwide-icu4x-data",
]
resolver = "2"

[workspace.package]
version = "41.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Shopify/worldwide"
